extends Node

signal new_day_started(day: int)
signal location_entered(id: String)
signal location_exited()
signal random_encounter_triggered(district: String)
signal battle_started(enemy_data: Dictionary)
signal battle_ended(result: String)
signal skill_executed(skill_id: String, caster: String, targets: Array)
signal all_out_attack_triggered()
signal heat_action_triggered(job: String)
signal merit_maxed()
signal karma_maxed()
signal player_died()
signal combo_count_changed(count: int)
signal vow_broken(vow_type: String)
signal cherry_affection_changed(val: int)
signal quest_updated(id: String, status: String)
signal dialogue_started(id: String)
signal dialogue_ended()
signal skill_unlocked(skill_name: String)
signal skill_learnable(skill_name: String)
signal achievement_unlocked(achievement_id: String)
